### PR TITLE
Building with Responsive Design

### PR DESCRIPTION
**Pull request by vichuge**
This project consists of replicating the "The Next Web" website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS : CHANGES REQUIRED :recycle:  :red_circle: 

Hello there @vichuge :wave:  :wave: this is impressive work you did on this project. It looks similar to the original one :clap:  :clap: . Before we can mark this project as complete let's work on the following:

#### Navigation bar
###### Medium version changes

* [x] TWN logo appears at the leftmost part ([link to page](https://thenextweb.com/))

###### Small version changes

* [x] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to seach icon) ([link to page](https://thenextweb.com/))
Check the screenshot below :arrow_down: 
- Original
s2

- Clone
s1

##### Top 3 articles section
###### Large version
* [x] It contains TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/))
Check the screenshot below :arrow_down: 
- Original
s3

- Clone
s4

##### Latest news section
###### Large version

* [x] It aligns 4 articles per row ([link to page](https://thenextweb.com/))

##### Latest Funding section
###### Large version
* [x] It aligns 4 articles per row ([link to page](https://thenextweb.com/))

##### Categories (Apps, Gear, Tech, etc) section

###### Large version
* [x] It aligns 3 category boxes per row ([link to page](https://thenextweb.com/))

##### Latest deals section
###### Large version
* [x] It aligns 4 deals per row ([link to page](https://thenextweb.com/))

##### Footer
* [x] It contains TNW logo with a copyright paragraph ([link to page](https://thenextweb.com/))

Thats all :smile: kindly submit another review when done
Regards
Peris Ndanu
Feel free to slack me (perisndanu) if you have any questions

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle: 
Hello team. Your page looks fantastic. Also thanks for making the requested changes. But, there is a small issue that needs to be fixed. I am giving a photo that shows the problem.

TNW
As you can see the footer is overflowing from the page for mobile view. There is an unnecessary margin on the right. Kindly fix this issue.

Again, you've made a great job. When you finish with the changes, please submit for another review. :100: 
If you have a question about the review, feel free to reach me via Slack.
Eyüp Sercan UYGUR

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Requested :recycle: 
Hello @vichuge 
You have made a great improvement so far on this project. 
It looks great.
There are still a few changes that you need to make.
- [x] The top 3 article section does of your project does not appear to be of the same size as it is in the original in both a tablet screen and small screen. Please try to make it look and have the same size as it is in the original.
- Original on a tablet screen
Screenshot from 2020-11-19 20-57-14
- Your project on a tablet screen
Screenshot from 2020-11-19 20-59-20
- original on a small screen 
Screenshot from 2020-11-19 21-00-43
- Your project on a small screen
Screenshot from 2020-11-19 21-01-15
- [x] Your footer is slightly different from how it looks in the original on a small screen. Try to make it look similar to how it appears on the original.
- Your footer on a small screen
Screenshot from 2020-11-19 21-02-36
- The original website footer on a small screen
Screenshot from 2020-11-19 21-06-48
Please request another review when you are done making those changes.
slack(@ebeagusamuel)

**Comment by mimipeshy** [comment]
### STATUS : CHANGES REQUIRED :recycle: 
Hello :wave:  its me again :smile: , congratulations on making the changes suggested by the TSE's. I really want to approve it but we still have to change one more thing:

#### Top  3 articles section
- Mobile view
- [x]  Remove the TNW logo.
- [x] Give the articles equal height.

That's all :smile: kindly submit another review when done
Regards
Peris Ndanu
Feel free to slack me (perisndanu) if you have any questions

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

### Hi @vichuge 

Good job implementing the change as requested by previous TSEs :+1: 
However, there are some changes that need to be made before this project can be approved.

## [REQUIRED]
**Mobile view**

- The text in the latest news section are to be aligned to the top, not bottom.
- The hard fork section has too much margin to the top

**Desktop view**

- The different section title on the page, i.e latest news, latest funding rounds on index.co., hard fork, etc should have no margin/padding to the left 

### Implement those changes and submit for another code review.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://raw.githack.com/vichuge/6-the-next-web/feature/index.html#) shows a good understanding Responsive Design. :100:
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job ! @vichuge :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
